### ISSUE TITLE
Test with command example

### ISSUE THREAD

**Issue by thanghl** [cannonbeach/ott-packager#15]
![image](https://user-images.githubusercontent.com/13869473/54002058-ed560380-417f-11e9-90b9-297cb8fe1117.png)
 Hi i don't what error out put, how i can fix, thanks so much

**Comment by cannonbeach** [comment]
I can't see the entire command line from your image, but that specific error message indicates you didn't include the output mode.  Try using:
--hls
and/or 
--dash

**Comment by thanghl** [comment]
Thansk for answer, I have new problem  :  



mpegts, from 'udp://225.50.5.5:1234':
  Duration: N/A, start: 2855.988644, bitrate: N/A
  Program 1
    Stream #0:0[0x28]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg, top first), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 50 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x29]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 126 kb/s
[root@Unifed ott-packager]#  ./fillet --sources 2 --ip 225.50.5.5:1234 --interface lo --window 5 --segment 5 --manifest /var/www/html/hls --identity 1000 --hls
STATUS: Source 0 IP: 225.50.5.5:1234
STATUS: Using supplied interface: lo
STATUS: Using window size: 5
STATUS: Using segment length: 5
STATUS: Using supplied manifest directory: /var/www/html/hls
STATUS: Using config identity: 1000

ERROR: INVALID IP ADDRESS:

Error: signal 11:
./fillet[0x404215]
/lib64/libc.so.6(+0x36280)[0x7f97b4ca1280]
/lib64/libc.so.6(cfree+0x1c)[0x7f97b4cf059c]
./fillet[0x40afb1]
./fillet[0x40b89c]
./fillet[0x416169]
./fillet[0x403d1b]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f97b4c8d3d5]
./fillet[0x40413d]

![image](https://user-images.githubusercontent.com/13869473/54004346-d2878d00-4187-11e9-8c22-1aac82707f9e.png)

**Comment by cannonbeach** [comment]
Please be sure to supply 2 IP addresses and ports (since you've indicated
you have 2 sources):

./fillet --sources 2 --ip 225.50.5.5:1234,225.50.5.5:1235 --interface lo
--window 5 --segment 5 --manifest /var/www/html/hls --identity 1000 --hls

You may also have trouble receiving multicast traffic on the interface of
"lo".

**Comment by thanghl** [comment]
I change it, ok if have drm how to do it , 

DRM systems:
Widevine
PlayReady¹
FairPlay¹
Marlin¹

Are you have test another multi drm ?? 

Thanks for all :)

**Comment by cannonbeach** [comment]
Thanks for the information on the routing issues you are having.  If you haven't already, please make sure you have the multicast route setup:
sudo route add -net 224.0.0.0 netmask 240.0.0.0 dev eth0

I have not had problems with Ubuntu 16 and Kernel 4.4 receiving multicast from a few different sources.  I will check the IGMP join code to see if there is anything that might be missing.  Which Linux distribution and Kernel are you using?

As for DRM, I have not implemented any of those systems yet.  I will start to look at them after I get the core features done for an initial v1.0 release.
Thanks!
