### ISSUE TITLE
Documentation for setup

### ISSUE THREAD

**Issue by sachin0606** [cannonbeach/ott-packager#18]
HI, 

thanks for the project, i want to setup this environment for internal UDP sources and start streaming. can you give me from scratch setup application and configuration documentation.

**Comment by cannonbeach** [comment]
Thank you for your interest.

Please review the documentation on the README.md front page which provides
a QuickStart along with command parameters and sample command line
configurations.  There is additional information available on the Wiki
pages for a more advanced setup using Docker.  After you review that
information please let me know if you have any specific questions.
