### ISSUE TITLE
No Source Signal

### ISSUE THREAD

**Issue by marciocamello** [cannonbeach/ott-packager#20]
SESSION:1 (TSRECEIVE) WARNING: NO SOURCE SIGNAL PRESENT (SOCKET:3) 127.0.0.1:4000:lo (142

I cant receive signal in my server.

**Comment by cannonbeach** [comment]
Please make sure you have a transport stream signal on the loop back
interface (lo) going to port 4000.

You can verify your signal is present using tcpdump as follows:
sudo tcpdump -n udp -i lo

What are you using as your source?

**Comment by marciocamello** [comment]
ffmpeg -re -i <input>  -pix_fmt yuv420p -c:v copy -c:a copy -f mpegts "udp://ip:4000"

tcpdump output

tcpdump: listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes

**Comment by cannonbeach** [comment]
Please make sure you re-stream to the loopback interface (which 127.0.0.1) otherwise the traffic may end up on a different interface such as eth0.

Here is the command line I used to test:
ffmpeg -re -i input.ts -c:v copy -c:a copy -f mpegts udp://127.0.0.1:4000?pkt_size=1316

**Comment by marciocamello** [comment]
Thank you, works, my interface is esn3, so i sendo to remote IP and works now.

**Comment by marciocamello** [comment]
Whats this LOG?

-------------- dumping out frame data ------------
DONE WITH SYNC LOCK
WAITING FOR SYNC THREAD TO STOP: 1
-------------- dumping out frame data ------------
-------------- dumping out frame data ------------
SESSION:1 (MAIN) STATUS: LEAVING SYNC THREAD - DISCONTINUITY
DONE WAITING FOR SYNC THREAD TO STOP
STATUS: RESTARTING FRAME SYNC THREAD
SESSION:1 (MAIN) STATUS: STARTING NEW SYNC THREAD
STATUS: RECEIVE_FRAME (H264/HEVC : 0): TYPE: 2 PTS:     2197124460 DTS:              0 KEY:

If show this log, dont generate ts files anymore.

**Comment by cannonbeach** [comment]
I'd have to see the full log to really understand the issue, but from what I can tell it looks like there is a discontinuity in your source stream that is causing the core sync thread to restart.  The core sync thread is supposed to restart on an unrecoverable discontinuity, but it should continue to process frames after that event.  Did the application exit or hang?

If you're still having trouble, please send me a short capture of your source and I can debug the issue.
