### ISSUE TITLE
Docker with webapp dont receive --hls params to fillet

### ISSUE THREAD

**Issue by marciocamello** [cannonbeach/ott-packager#21]
ILLET: ERROR: Please select TS output (--hls) and/or fMP4 output mode (--dash) OR YouTube DASH publishing mode

**Comment by cannonbeach** [comment]
Since you are using the webapp, could you please send me the config file you are using?  It'll be located in /var/tmp/configs.  It will have a .json extension.  Thanks.

**Comment by marciocamello** [comment]
This error in transcoder 

gcc -g -c -O2 -m64 -Wall -Wfatal-errors -funroll-loops -Wno-deprecated-declarations -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -DENABLE_TRANSCODE -I./include -I./cbfdkaac/libAACenc/include -I./cbfdkaac/libSYS/include -I./x265_3.0/build/linux -I./cblibcurl/include/curl ./source/transaudio.c
In file included from ./source/transaudio.c:47:0:
./source/../cbffmpeg/libavresample/avresample.h:102:10: fatal error: libavresample/version.h: No such file or directory
 #include "libavresample/version.h"

And /var/tmp/config has empty

**Comment by cannonbeach** [comment]
Since you are using the webapp, could you please send me the config file
you are using?  It’ll be located in /var/tmp/configs?   It will have a
.json extension.  Thanks!

**Comment by marciocamello** [comment]
Yeah, i am run webapp, and in /var/tmp/configs are not exist any file *.json.

**Comment by marciocamello** [comment]
Look 

[https://prnt.sc/nvtnhu](https://prnt.sc/nvtnhu)

**Comment by cannonbeach** [comment]
I forgot to include some additional packages in the setuptranscode.sh script that I already had installed. I also had a version ffmpeg installed with headers in my system directory, so I had to add a directory to the Makefile to point to the correct location.

Please do a code update and rerun:
1.  ./setuptranscode.sh
2. Edit the Makefile to set ENABLE_TRANSCODE
3. make clean
4. make

Then please follow the instructions for the webapp to get the Docker container built with the updated executable. 
Please let me know if you run into anymore issues.

**Comment by cannonbeach** [comment]
And don't forget to rebuild the Docker image if you plan to run the webapp....

1. cp fillet ./docker
2. cd ./docker
3. sudo docker build -t dockerfillet .

**Comment by marciocamello** [comment]
Works now, testing and i will report to better image to docker, and latest ffmpeg version maybe
