### ISSUE TITLE
SRT support

### ISSUE THREAD

**Issue by cannonbeach** [cannonbeach/ott-packager#24]
Add SRT support to the input (see libsrt project)

**Comment by PhilGourgand** [comment]
Input SRT support would be very very appreciated

**Comment by cannonbeach** [comment]
Hi Phil, Thank you for your interest.  Are you transcoding or just
packaging a source?  I am finishing up some other small improvements, but
could take a look at that next in the coming month.  Is there a subset of
the SRT that would be suitable for your application?   Listener, Caller,
and/or Rendezvous mode?

**Comment by cannonbeach** [comment]
Please use my opensrthub project for SRT inputs
