### ISSUE TITLE
unable to build when transcoding enabled

### ISSUE THREAD

**Issue by sfahadshahzad** [cannonbeach/ott-packager#26]
Hi,

When I manual update the makefile to enable transcoding got errors.

g++ fillet.o crc.o tsdecode.o fgetopt.o mempool.o transvideo.o transaudio.o dataqueue.o udpsource.o tsreceive.o hlsmux.o mp4core.o background.o cJSON.o cJSON_Utils.o webdav.o esignal.o -L./  ./cbffmpeg/libavfilter/libavfilter.a ./cbffmpeg/libavformat/libavformat.a ./cbffmpeg/libswscale/libswscale.a ./cbffmpeg/libavcodec/libavcodec.a ./cbffmpeg/libavutil/libavutil.a ./cbffmpeg/libavresample/libavresample.a ./cbffmpeg/libswresample/libswresample.a ./cbx264/libx264.a ./cbfdkaac/.libs/libfdk-aac.a ./cblibcurl/./lib/.libs/libcurl.a ./x265_3.0/build/linux/libx265.a -lz -ldl -lnuma -lcrypto -lssl -lm -lpthread -o fillet
./cblibcurl/./lib/.libs/libcurl.a(libcurl_la-url.o): In function `conn_free':
url.c:(.text+0x13f): undefined reference to `idn2_free'
url.c:(.text+0x15b): undefined reference to `idn2_free'
url.c:(.text+0x177): undefined reference to `idn2_free'
url.c:(.text+0x193): undefined reference to `idn2_free'
./cblibcurl/./lib/.libs/libcurl.a(libcurl_la-url.o): In function `idnconvert_hostname.isra.3':
url.c:(.text+0x5a8): undefined reference to `idn2_check_version'
url.c:(.text+0x5c5): undefined reference to `idn2_lookup_ul'
url.c:(.text+0x5de): undefined reference to `idn2_strerror'
./cblibcurl/./lib/.libs/libcurl.a(libcurl_la-url.o): In function `Curl_connect':
url.c:(.text+0x4ca4): undefined reference to `idn2_free'
url.c:(.text+0x4cc0): undefined reference to `idn2_free'
url.c:(.text+0x4e95): undefined reference to `idn2_free'
url.c:(.text+0x4eb1): undefined reference to `idn2_free'
./cblibcurl/./lib/.libs/libcurl.a(libcurl_la-version.o): In function `curl_version':
version.c:(.text+0xa9): undefined reference to `idn2_check_version'
version.c:(.text+0xb5): undefined reference to `idn2_check_version'
./cblibcurl/./lib/.libs/libcurl.a(libcurl_la-version.o): In function `curl_version_info':
version.c:(.text+0x150): undefined reference to `idn2_check_version'
./cblibcurl/./lib/.libs/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_disconnect':
curl_rtmp.c:(.text+0x2c): undefined reference to `RTMP_Close'
curl_rtmp.c:(.text+0x34): undefined reference to `RTMP_Free'
./cblibcurl/./lib/.libs/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_connect':
curl_rtmp.c:(.text+0xd4): undefined reference to `RTMP_Connect1'
./cblibcurl/./lib/.libs/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_send':
curl_rtmp.c:(.text+0x162): undefined reference to `RTMP_Write'
./cblibcurl/./lib/.libs/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_recv':
curl_rtmp.c:(.text+0x1ab): undefined reference to `RTMP_Read'
./cblibcurl/./lib/.libs/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_do':
curl_rtmp.c:(.text+0x227): undefined reference to `RTMP_ConnectStream'
./cblibcurl/./lib/.libs/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_setup_connection':
curl_rtmp.c:(.text+0x2aa): undefined reference to `RTMP_Alloc'
curl_rtmp.c:(.text+0x2bf): undefined reference to `RTMP_Init'
curl_rtmp.c:(.text+0x2cc): undefined reference to `RTMP_SetBufferMS'
curl_rtmp.c:(.text+0x2df): undefined reference to `RTMP_SetupURL'
curl_rtmp.c:(.text+0x304): undefined reference to `RTMP_Free'
collect2: error: ld returned 1 exit status
Makefile:42: recipe for target 'fillet' failed
make: *** [fillet] Error 1

without transcoding build properly.

Regards,

Fahad

**Comment by cannonbeach** [comment]
Please post the output of the following:
uname -a
gcc --version
and email me the config.log from your ./cblibcurl directory.

I don't have idn or rtmp set to be configured in the libcurl configuration, so it's possible the configuration script is autodetecting those packages which are already installed on your system.  I'll be able to tell by reviewing your config.log from curl.

**Comment by cannonbeach** [comment]
I pushed up a change to prevent auto-configuration of libidn and librtmp in the libcurl setup.  I suspect you have those third party packages installed on your system and the libcurl configure script is detecting them.  Please update your setuptranscode.sh script and re-run.  Let me know if you still have problems after that.
