### ISSUE TITLE
installation Error

### ISSUE THREAD

**Issue by Marco-LB** [cannonbeach/ott-packager#32]
Hi I'm trying to install it on a debian server 9, unfortunately I only have this version of debian.
when I try to run the make clean and make command (after removing # from # ENABLE_TRANSCODE = 1)

cannonbeach @ insanitywave: $ make clean
cannonbeach @ insanitywave: $ make
the system gives me this error:
Makefile:17: *** recipe commences before first target.  Stop.

**Comment by cannonbeach** [comment]
Can you please check that you ran the "setuptranscode.sh" script and that
it completed successfully?   Line 17 in the Makefile is checking for the
libfdk_aac and it appears that it isn't installed.

**Comment by Marco-LB** [comment]
hi thanks for the quick reply, when I start setuptranscode.sh it completes successfully.
I have seen the script and manually started the installation of "fdk-aac" and it is not successful, I have installed Automake and I was able to finish it without problems, now I have restarted the setuptranscode.sh script, I am waiting for the result. as soon as I can I update you

**Comment by cannonbeach** [comment]
I am glad you figured out the issue.  I only build and test using Ubuntu so you may run into other issues with slight package differences when using Debian Server 9.
