### ISSUE TITLE
NOT GRABBING AUDIO: DELTA

### ISSUE THREAD

**Issue by punyahenry** [cannonbeach/ott-packager#33]
Hi, i try to use inline command 
./fillet --sources 3 --ip 239.1.1.1:5001,239.1.1.1:5002,239.1.1.1:5003 --interface ens192 --window 5 --segment 10 --manifest /var/www/html/hls --identity 1000 --hls

have console log 

STATUS: RECEIVE_FRAME (H264/HEVC : 0): TYPE: 2 PTS:      292903200 DTS:      292892400 KEY:1
NOT GRABBING AUDIO: DELTA:-29420 (CVT:292791600 CAT:292821020) AS:1 ASE:3 VSE:56
NOT GRABBING AUDIO: DELTA:-25820 (CVT:292795200 CAT:292821020) AS:1 ASE:3 VSE:55
NOT GRABBING AUDIO: DELTA:-25820 (CVT:292795200 CAT:292821020) AS:1 ASE:3 VSE:54
NOT GRABBING AUDIO: DELTA:-22220 (CVT:292798800 CAT:292821020) AS:1 ASE:3 VSE:53
NOT GRABBING AUDIO: DELTA:-22220 (CVT:292798800 CAT:292821020) AS:1 ASE:3 VSE:52
NOT GRABBING AUDIO: DELTA:-18620 (CVT:292802400 CAT:292821020) AS:1 ASE:3 VSE:51
NOT GRABBING AUDIO: DELTA:-18620 (CVT:292802400 CAT:292821020) AS:1 ASE:3 VSE:50
NOT GRABBING AUDIO: DELTA:-15020 (CVT:292806000 CAT:292821020) AS:1 ASE:3 VSE:49
NOT GRABBING AUDIO: DELTA:-15020 (CVT:292806000 CAT:292821020) AS:1 ASE:3 VSE:48
NOT GRABBING AUDIO: DELTA:-11420 (CVT:292809600 CAT:292821020) AS:1 ASE:3 VSE:47
NOT GRABBING AUDIO: DELTA:-11420 (CVT:292809600 CAT:292821020) AS:1 ASE:3 VSE:46
NOT GRABBING AUDIO: DELTA:-7820 (CVT:292813200 CAT:292821020) AS:1 ASE:3 VSE:45
NOT GRABBING AUDIO: DELTA:-7820 (CVT:292813200 CAT:292821020) AS:1 ASE:3 VSE:44
NOT GRABBING AUDIO: DELTA:-4220 (CVT:292816800 CAT:292821020) AS:1 ASE:3 VSE:43
NOT GRABBING AUDIO: DELTA:-4220 (CVT:292816800 CAT:292821020) AS:1 ASE:3 VSE:42
NOT GRABBING AUDIO: DELTA:-620 (CVT:292820400 CAT:292821020) AS:1 ASE:3 VSE:41
NOT GRABBING AUDIO: DELTA:-620 (CVT:292820400 CAT:292821020) AS:1 ASE:3 VSE:40
STATUS: RECEIVE_FRAME (H264/HEVC : 0): TYPE: 2 PTS:      292903200 DTS:      292892400 KEY:1

after play on vlc no audio and video is mess, for audio encoding MPEG-AAC and video MPEG-4.

Any one have facing problem same with me?

**Comment by cannonbeach** [comment]
Were you able to get this resolved?

**Comment by punyahenry** [comment]
still not solve n don't know what to do, to solve this issue

**Comment by cannonbeach** [comment]
What happens when you only use one source instead of three?  Is the behavior any different?
