### ISSUE TITLE
Makefile:18: *** recipe commences before first target

### ISSUE THREAD

**Issue by Yoda70** [cannonbeach/ott-packager#35]
Hi,

I getting an error on first make command (ubuntu srv 20.04):

fulvio@transcoder:~/ott-packager$ make
Makefile:18: *** recipe commences before first target.  Stop.
fulvio@transcoder:~/ott-packager$ 

It should be on this line:
$(error Please make sure FDK-AAC is installed - missing ./cbfdkaac/.libs/libfdk-aac.a - please run setuptranscode.sh)

How I can fix it?

Thank you,
Fulvio

**Comment by cannonbeach** [comment]
Did you run the setuptranscode.sh script?

**Comment by Yoda70** [comment]
`fatal: destination path './cbffmpeg' already exists and is not an empty directory.

No NVIDIA Hardware Found
Installing x264 from cannonbeach fork
fatal: destination path './cbx264' already exists and is not an empty directory.
Unknown option --disable-shared, ignored

libtool:   error: 'libSACenc/src/sacenc_bitstream.lo' is not a valid libtool object
make: *** [Makefile:1490: libfdk-aac.la] Error 1
ERROR: libfdk-aac.a was not compiled correctly - aborting installation!`

**Comment by Yoda70** [comment]
I get the error showed running the setuptranscode.sh script

**Comment by cannonbeach** [comment]
Can you go into the cbfdkaac directory and run the following one at a time?

./autogen.sh
./configure --prefix=/usr --enable-static --with-pic
make

and let me know where it fails.  It is possible the configure script failed
due to a missing package or different build toolchain.  What version of
Linux are you running?

**Comment by Yoda70** [comment]
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal


   Static hostname: transcoder
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 5392b38e44aa40bab1fcfbf3cf9c278d
           Boot ID: f78180717df0492daf1d28fa8e555204
    Virtualization: oracle
  Operating System: Ubuntu 20.04.4 LTS
            Kernel: Linux 5.4.0-107-generic
      Architecture: x86-64

**Comment by Yoda70** [comment]
Yes, also this command fails

**Comment by cannonbeach** [comment]
Are you running desktop or server?  Could you send me your entire script and build log?

**Comment by Yoda70** [comment]
I used ubuntu server on virtual box vm, I tried with server 18 version and
20.04 without upgrade the OS after the installation and it works.
Attached the script used in the faulty installation.




Il giorno mer 13 apr 2022 alle ore 17:17 Will ***@***.***> ha
scritto:

**Comment by cannonbeach** [comment]
What do you mean without upgrade?  I have not run things using virtual box vm.

**Comment by Yoda70** [comment]
After the installation I did apt update and apt upgrade, on another vm without upgrade it works with ubuntu server 20.04 or 18
I’m able to run in virtual box, using a vm with strong resorces RAM and core.

Inviato da iPhone

**Comment by cannonbeach** [comment]
Can you send me the entire output log of your compilation?
