### ISSUE TITLE
Makefile:18: *** recipe commences before first target.  Stop.

### ISSUE THREAD

**Issue by serenityavondale** [cannonbeach/ott-packager#37]
I keep getting this same error no matter what I try.  I have followed install instructions implicitly as well as following the instructions in the previous ticket.  Nothing seems to work.  Running ubuntu 20.04

**Comment by cannonbeach** [comment]
Line 18 of the Makefile is:
           $(error Please make sure FDK-AAC is installed - missing
./cbfdkaac/.libs/libfdk-aac.a - please run setuptranscode.sh)

Did you run the setuptranscode.sh script?

**Comment by serenityavondale** [comment]
That worked! Thank you so much for that.
